-- MySQL Script generated by MySQL Workbench
-- 07/13/17 10:49:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema TrafficEnger
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TrafficEnger
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TrafficEnger` DEFAULT CHARACTER SET utf8 ;
USE `TrafficEnger` ;

-- -----------------------------------------------------
-- Table `TrafficEnger`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrafficEnger`.`test` (
  `idtest` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  PRIMARY KEY (`idtest`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
